const reasons = [
"Your beautiful smile brightens every day.",
"Your laugh is my favorite sound.",
"You make my heart feel at peace.",
"You always know how to make me smile.",
"You make ordinary days feel special.",
"You are the first person I want to talk to every day.",
"You always support me.",
"You believe in me even when I doubt myself.",
"You make me want to become a better person.",
"Your kindness inspires me.",
"You have the most beautiful heart.",
"You make me feel understood.",
"You accept me for who I am.",
"You never stop caring about me.",
"You make distance feel smaller.",
"Your voice calms my mind.",
"You make me feel safe.",
"You make me feel loved every single day.",
"I love your adorable expressions.",
"I love your little habits.",
"Your happiness means everything to me.",
"You make every memory unforgettable.",
"I love the way you look at me.",
"You make me laugh even on my worst days.",
"You are always there when I need you.",
"You make my life brighter.",
"You make my heart race.",
"You are my favorite notification.",
"I love hearing your stories.",
"You are my comfort.",
"You are my peace.",
"You are my safe place.",
"I can be completely myself with you.",
"You encourage me to chase my dreams.",
"You always listen to me.",
"You respect my feelings.",
"You trust me.",
"You make me feel important.",
"I love your caring nature.",
"You make every conversation enjoyable.",
"You never fail to surprise me.",
"You make my future look beautiful.",
"You inspire me every day.",
"You are incredibly thoughtful.",
"I admire your strength.",
"You have a beautiful soul.",
"I love your honesty.",
"You are wonderfully patient.",
"You always know how to cheer me up.",
"I love making memories with you.",
"You understand me without words.",
"You make every moment magical.",
"You make me feel lucky.",
"You are my biggest blessing.",
"I love dreaming about our future.",
"You bring happiness wherever you go.",
"You are my favorite person.",
"I love spending time with you.",
"You always make me feel special.",
"You never give up on us.",
"You love me despite my flaws.",
"You make me stronger.",
"You motivate me every day.",
"You make my world complete.",
"You have the cutest smile.",
"You have the sweetest heart.",
"You are beautiful inside and out.",
"I love your confidence.",
"I admire your courage.",
"You make me proud.",
"You are my sunshine on cloudy days.",
"You make my heart feel full.",
"I love every little thing about you.",
"You make me believe in forever.",
"You make every hug feel like home.",
"You are the reason I smile so much.",
"You make life more meaningful.",
"You are my favorite memory.",
"You are my greatest adventure.",
"You make every goodbye difficult.",
"Every hello from you is worth waiting for.",
"I love your beautiful eyes.",
"You make me feel complete.",
"You make my heart happy.",
"You are my dream come true.",
"I love the way you care for me.",
"You always make me feel appreciated.",
"You make my life colorful.",
"I love sharing everything with you.",
"You make every celebration special.",
"You are my forever person.",
"I love growing with you.",
"I love making plans with you.",
"You make every tomorrow exciting.",
"You make me believe in true love.",
"You are the best part of my life.",
"I choose you today.",
"I will choose you tomorrow.",
"I will choose you every single day.",
"Because you are you—and that is more than enough for me to love you forever. ❤️"
];

